<?php

namespace les2MainsBundle\Repository;

/**
 * intervenantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class intervenantsRepository extends \Doctrine\ORM\EntityRepository
{
}
