<?php

namespace les2MainsBundle\Repository;

/**
 * lieuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lieuxRepository extends \Doctrine\ORM\EntityRepository
{
}
