<?php

namespace les2MainsBundle\Repository;

/**
 * NousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NousRepository extends \Doctrine\ORM\EntityRepository
{
}
