<?php

namespace les2MainsBundle\Repository;

/**
 * TVARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TVARepository extends \Doctrine\ORM\EntityRepository
{
}
