<?php

namespace BlogBundle\Repository;

/**
 * IntervenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervenantRepository extends \Doctrine\ORM\EntityRepository
{
}
