<?php

namespace CommerceBundle\Repository;

/**
 * MarchandiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarchandiseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $evenement
     * @return array
     */
    public function getMarchandiseById($evenement)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.evenement = :event')
            ->join('m.product', 'p')
            ->orderBy('p.name')
            ->setParameter('event', $evenement)
        ;
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $evenement
     * @param $product
     * @return mixed
     */
    public function getCheckMarchandiseById($evenement, $product)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.evenement = :event')
            ->join('m.product', 'p')
            ->andWhere('p.id = :product')
            ->setParameters(array(
                'event' =>$evenement,
                'product'=>$product
            ))
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }

}
