<?php

namespace CommerceBundle\Repository;

/**
 * MarchandiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarchandiseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMarchandiseById($evenement)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.evenement = :event')
            ->join('m.product', 'p')
            ->orderBy('p.name')
            ->setParameter('event', $evenement)
        ;
        return $qb->getQuery()->getResult();
    }
}
