<?php

namespace CoreBundle\Repository;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActivities()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a')
            ->join('a.event','e')
            ->where('e.id IS NOT NULL');

        return $qb->getQuery()->getresult();
    }
}
