<?php

namespace CoreBundle\Repository;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindOneById($id){
        $qb = $this->createQueryBuilder('activite');
        $qb->select('activite')
            ->where('activite.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
    }
}
