<?php

namespace CoreBundle\Repository;

/**
 * ActiviteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
