<?php

namespace CoreBundle\Repository;

/**
 * ActiviteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteTypeRepository extends \Doctrine\ORM\EntityRepository
{

    public function getActivitiesType()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a')
            ->join('a.activites','t')
            ->where('t.id IS NOT NULL');

        return $qb->getQuery()->getresult();
    }
}