<?php

namespace CoreBundle\Repository;

/**
 * OurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OurRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function myFindSingleOurPage()
    {
        $qb=$this->createQueryBuilder('o');
        $qb->select('o');
        //transforem du DQL en SQl
        return $qb->getQuery()->getSingleResult();
    }
}
