<?php

namespace CoreBundle\Repository;

/**
 * OurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OurRepository extends \Doctrine\ORM\EntityRepository
{
}
